commitFormat: angular
title: "testr release"
branch:
  master: release
  rc: rc
  beta: beta
  alpha: alpha
changelog:
  printAll: false
  template: ''
  templatePath: ''
release: 'github'
assets:
  - name:
    compress:
provider:
  name: "GitHub"
  repo: ""
  user: ""
  customURL: ""
