release: 'github'
github:
  repo: "go-semantic-release"
  user: "nightapes"
commitFormat: angular
branch:
  master: release
assets:
  - name: ./build/go-semantic-release
    compress: false
  - name: ./build/go-semantic-release.exe
    compress: false