commitFormat: angular
title: "testr release"
branch:
  master: release
  rc: rc
  beta: beta
  alpha: alpha
  add_git_releases: alpha
changelog:
  printAll: false
  template: ''
  templatePath: ''
release: 'github'
assets:
  - name:
    compress:
github:
  repo: "go-semantic-release"
  user: "nightapes"
  customUrl: ""
