commitFormat: angular
branch:
  master: release
  sd: rc
  sds: beta
  travis: alpha
changelog:
  print: all/compact
  template: ''
  templatePath: ''
release: 'github'
github:
  url: ''
gitlab:
  url: ''
