commitFormat: angular
branch:
  master: release
  rc: rc
  beta: beta
  alpha: alpha
changelog:
  printAll: false
  template: ''
  templatePath: ''
release: 'github'
github:
  url: ''
gitlab:
  url: ''
