dist: xenial

language: go
go:
  - 1.12.x
gobuild_args: -x -ldflags
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

services:
- docker

notifications:
  email: false

git:
  depth: 1

env:
  - GO111MODULE=on

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0

script:
  - golangci-lint run ./...
  - go test -v ./...
  - go build -o build/go-semantic-release ./cmd/go-semantic-release/
  - GOOS=windows GOARCH=386 go build -o build/go-semantic-release.exe ./cmd/go-semantic-release/

branches:
  except:
    - /^v\d+\.\d+\.\d+$/